---
- name: Install Dovecot
  yum: name={{ item }} state=present
  with_items:
    - dovecot

- name: Configure Dovecot
  blockinfile:
    dest: /etc/dovecot/dovecot.conf
    backup: yes
    marker: "# Modifications for DeFaria.com {mark}"
    insertafter: EOF
    content: |
      passdb {
        driver = pam 
      }
      service auth {
        unix_listener /var/spool/postfix/private/auth {
          mode = 0660
          user = postfix
          group = postfix
        }
        user = root
      }
  notify: Restart Dovecot

- name: Enable Dovecot
  service: name=dovecot state=started enabled=yes
