---
- name: Install Dovecot
  yum: name={{item}} state=present
  with_items:
    - dovecot

- name: Configure Dovecot
  template: src=defaria.dovecot.conf dest=/etc/dovecot/conf.d/defaria.dovecot.conf
  notify: Restart Dovecot

- name: Enable Dovecot
  service: name=dovecot state=started enabled=yes
