#!/usr/bin/expect --
################################################################################
#
# File:         showchannel.exp
# Description:  Tests show channel command
# Author:       Andrew@DeFaria.com
# Created:      Fri Jun  6 15:37:15 PDT 2003
# Language:     Expect
# Test Class:	CLI
#
# (c) Copyright 2003, Andrew@DeFaria.com, all rights reserved
#
################################################################################
set test_base "/dview/defaria_default/Tools/testing"

source "$test_base/bin/TestPkg.tcl"

catch {namespace import Test::*}

proc Setup {} {
  Start "show channel"
}

proc Run {} {
  set Test::result 1

  set more 1
  send "show channel 1/1.*\r"

  while {$more} {
    expect {
      $Test::success {
        set Test::result 0
	set more 0
      }
      "Q to Quit" {
        send "Q\r"
      }
    }
  }
}

proc CleanUp {} {
  End
}

# Main
Setup
Run
CleanUp
