#!/usr/bin/expect --
################################################################################
#
# File:         show8021pmap.exp
# Description:  Tests show 8021pmap command
# Author:       Andrew@DeFaria.com
# Created:      Fri Jun  6 15:37:15 PDT 2003
# Language:     Expect
# Test Class:	Sanity
#
# (c) Copyright 2003, Andrew@DeFaria.com, all rights reserved
#
################################################################################
set test_base "/dview/defaria_default/Tools/testing"
source "$test_base/bin/TestPkg.tcl"

catch {namespace import Test::*}

proc Setup {} {
  Start "show 8021pmap"
}

proc Run {} {
  set Test::result 1

  send "show 8021pmap all\r"

  expect {
    $Test::success {
      set Test::result 0
    }
  }
}

proc CleanUp {} {
  End
}

# Main
Setup
Run
CleanUp
