---
# This will create an OpenStack instance on DreamCompute.
# See: https://help.dreamhost.com/hc/en-us/articles/218925908-How-to-launch-a-DreamCompute-server-with-Ansible

# Hosts the playbook runs on
- hosts: localhost
  # Added vars_file to keep encrypted the secrets
  vars_files:
    - ../vars/secrets.yml
  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  # List of tasks
  tasks:
  - name: Provision CentOS 7

    # Define a server
    os_server:

      # Cloud authentication information
      auth:
        auth_url: https://iad2.dream.io:5000
        username: "{{dreamcompute_username}}"
        password: "{{dreamcompute_password}}"
        project_name: "{{dreamcompute_project}}"

      # VM details
      state: present
      name: defaria-test
      image: CentOS-7
      key_name: dreamcompute
      flavor: gp1.lightspeed
      network: public
      wait: yes
