---
- name: Install Apache and various support modules
  yum: name={{item}} state=latest
  with_items:
   - gitweb
   - httpd
   - mod_ssl

- name: Create Let's Encrypt directories
  file: path=/etc/letsencrypt/live/defaria.com recurse=true

- name: Configure Apache
  file: src=/opt/defaria.com/playbook/roles/web/files/{{item.src}} dest={{item.dest}} state=link
  with_items:
    - {src: 'defaria.conf',  dest: '/etc/httpd/conf.d/defaria.conf'}
    - {src: 'clearscm.conf', dest: '/etc/httpd/conf.d/clearscm.conf'}
    - {src: 'maps.conf',     dest: '/etc/httpd/conf.d/maps.conf'}
    - {src: 'songbook.conf', dest: '/etc/httpd/conf.d/songbook.conf'}
    - {src: 'cert.pem',      dest: '/etc/letsencrypt/live/defaria.com/cert.pem'}
    - {src: 'privkey.pem',   dest: '/etc/letsencrypt/live/defaria.com/privkey.pem'}
    - {src: 'chain.pem',     dest: '/etc/letsencrypt/live/defaria.com/chain.pem'}
  notify: Restart httpd

- stat: path=/var/www/html
  register: links

- name: Remove /var/www/html
  file:
    path: /var/www/html
    state: absent
  when:
    links.stat.islnk == False

- name: Configure symlinks
  file: src={{item.src}} dest={{item.dest}} state=link
  with_items:
    - {src: /opt/defaria.com, dest: '/var/www/html'}
    - {src: /opt/defaria.com, dest: '/web'}
  notify: Restart httpd

- name: Enable Apache
  service: name=httpd state=started enabled=yes

- name: Fix up /etc/php.ini
  copy:
    src: defaria.ini
    dest: /etc/php.d/defaria.ini
