---
- name: Install Perl
  yum: name={{item}} state=present
  with_items:
    - perl-DBD-MySQL
    - readline-devel   # For Term::ReadLine::Gnu

- name: Install cpanm dependencies
  yum: name={{item}} state=present
  with_items:
    - perl-devel
    - perl-CPAN

- name: Download cpanm
  get_url:
    url: http://cpanmin.us
    dest: /usr/bin/cpanm
    mode: 555

- name: Install cpanm module
  command: /usr/local/bin/cpanm App::cpanminus
  register: install_cpanm
  changed_when: False

- name: Install cpanm
  command: /usr/local/bin/cpanm App::cpanminus
  changed_when: True
  when: install_cpanm.stdout.find('cpanminus is up to date') == -1

- name: Install Perl Modules
  cpanm: name={{item}}
  with_items:
    - YAML
    - MIME::Entity
    - Term::ReadLine::Gnu