---
- name: Install system modules
  yum: name={{item}} state=present
  with_items:
    - dos2unix
    - gcc
    - git
    - mailx
    - MySQL-python
    - ntp
    - readline-devel
    - telnet
    - vim

- name: Enable NTP
  service: name=ntpd state=started enabled=yes

# Why is setting timezone so complicated?!? We have /etc/timezone, which should
# be linked to the appropriate timezone under /usr/share/zoneinfo, which I guess
# is used for when the machine reboots. Then there's the timezone variable TZ, 
# which doesn't seem like it's used anymore. PHP, of course, needs to have 
# timezone set in php.ini (or dirivative) and finally there's the timedatectl
# command which is new and seems to set the current timezone. Geeze guys, please
# settle on one method! 
- name: Check Current Timezone
  register: timezone
  command: timedatectl
  changed_when: False

- name: Set Current Timezone
  command: timedatectl set-timezone America/Los_Angeles
  changed_when: True
  when: timezone.stdout != "America/Los_Angeles"

- name: Set TZ variable
  lineinfile:
    path: /etc/environment
    regexp: '^TZ='
    line: 'TZ=America/Los_Angeles'

- name: Create defaria group
  group: name=defaria

- name: Create my user
  user: name=andrew group=defaria

- name: Create ~/.ssh
  file:
    path:  /home/andrew/.ssh
    owner: andrew
    group: defaria
    state: directory
    mode: 0700

- name: Set up ssh (private key)
  copy:
    src=/home/andrew/.ssh/id_ecdsa
    dest=/home/andrew/.ssh/id_ecdsa
    owner=andrew
    group=defaria
    mode=0600

- name: Set up ssh (puplic key)
  copy:
    src=/home/andrew/.ssh/id_ecdsa.pub
    dest=/home/andrew/.ssh/id_ecdsa.pub
    owner=andrew
    group=defaria
    mode=0644

- name: Set up ssh (authorized_keys)
  copy:
    src=/home/andrew/.ssh/id_ecdsa.pub
    dest=/home/andrew/.ssh/authorized_keys
    owner=andrew
    group=defaria
    mode=0644

- name: Create repo dirs
  file: path=/opt/{{item}} state=directory owner=andrew group=defaria mode=0755
  with_items:
    - clearscm
    - defaria.com
    - media
    - songbook 

- name: Pull my repos from github
  become: yes
  become_user: andrew
  git: repo=https://github.com/adefaria/{{item}}.git dest=/opt/{{item}}/.
  with_items:
    - clearscm
    - defaria.com
    - media
    - songbook

- name: Pull getssl repo from github
  git: 
    repo: https://github.com/srvrco/getssl.git
    dest: /opt/getssl

- name: Link RC
  become: yes
  become_user: andrew
  file: src=/opt/clearscm/rc dest=/home/andrew/.rc state=link

- name: Check setup_rc (user)
  become: yes
  become_user: andrew
  command: /home/andrew/.rc/setup_rc
  register: setup_rc
  changed_when: False

- name: Set up RC (user)
  become: yes
  become_user: andrew
  command: /home/andrew/.rc/setup_rc
  changed_when: True
  when: setup_rc.stdout != ''

- name: Link RC
  file: src=/opt/clearscm/rc dest=/root/.rc state=link

- name: Check setup_rc (root)
  command: /root/.rc/setup_rc
  register: setup_rc
  changed_when: False

- name: Set up RC (root)
  command: /root/.rc/setup_rc
  changed_when: True
  when: setup_rc.stdout != ''

- name: Create ~andrew/.nag directory
  file:
    path:  /home/andrew/.nag
    owner: andrew
    group: defaria
    state: directory

- name: Set up nag list
  template:
    src:   nag.list
    dest: /home/andrew/.nag/list
    owner: andrew
    group: defaria

- name: Set up user crontab
  template:
    src:   crontab.andrew
    dest:  /var/spool/cron/andrew
    owner: andrew
    group: defaria

- name: Set up user crontab
  template:
    src:   crontab.root
    dest:  /var/spool/cron/root
    owner: root
    group: root

- name: Set up sudo
  copy:
    src=../templates/10-andrew
    dest=/etc/sudoers.d/10-andrew
    owner=root
    group=root
    mode=0440
