---
- name: Install system modules
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - git
    - mailx
    - vim

- name: Create defaria group
  group: name=defaria

- name: Create my user
  user: name=andrew group=defaria

# How do you do this really when Ansible requires ssh access in the first place?

- name: Set up ssh (private key)
  copy:
    src=/home/andrew/.ssh/id_ecdsa
    dest=/home/andrew/.ssh/id_ecdsa
    owner=andrew
    group=defaria
    mode=0400

- name: Set up ssh (puplic key)
  copy:
    src=/home/andrew/.ssh/id_ecdsa.pub
    dest=/home/andrew/.ssh/id_ecdsa.pub
    owner=andrew
    group=defaria
    mode=0644

- name: Set up ssh (authorized_keys)
  copy:
    src=/home/andrew/.ssh/id_ecdsa.pub
    dest=/home/andrew/.ssh/authorized_keys
    owner=andrew
    group=defaria
    mode=0400

- name: Pull repos from github
  become: yes
  become_user: andrew
  git: repo=https://github.com/adefaria/{{item}}.git dest=/opt/{{item}}
  with_items:
    - clearscm
    - defaria.com
    - media
    - songbook

- name: Link RC
  file: src=/opt/clearscm/rc dest=/home/andrew/.rc state=link

- name: Check setup_rc
  become_user: andrew
  command: /home/andrew/.rc/setup_rc
  register: setup_rc
  changed_when: False

- name: Set up RC
  become_user: andrew
  command: /home/andrew/.rc/setup_rc
  changed_when: True
  when: setup_rc.stdout != ''

- name: Create ~andrew/.nag directory
  file:
    path:  /home/andrew/.nag
    owner: andrew
    group: defaria
    state: directory

- name: Set up nag list
  template:
    src:   nag.list
    dest: /home/andrew/.nag/list
    owner: andrew
    group: defaria

- name: Set up user crontab
  template:
    src:   crontab.andrew
    dest:  /var/spool/cron/andrew
    owner: andrew
    group: defaria

- name: Set up user crontab
  template:
    src:   crontab.root
    dest:  /var/spool/cron/root
    owner: root
    group: root

- name: Set up sudo
  copy:
    src=../templates/10-andrew
    dest=/etc/sudoers.d/10-andrew
    owner=root
    group=root
    mode=0440