---
- include_vars: secrets.yml

- name: Install MariaDB
  become: true
  become_user: root
  yum: name={{item}} state=present
  with_items:
    - mariadb
    - mariadb-server

- name: Enable MariaDB
  service: name=mariadb state=started enabled=yes

# Secure MySQL root
- name: Set MySQL root password
  mysql_user:
    login_user: root
    login_password: '{{mysql_root_password}}'
    name: root
    password: '{{mysql_root_password}}'
    check_implicit_admin: yes

- name: Setup ~root.my.cnf
  template: src=root.my.cnf dest=/root/.my.cnf mode=0400

- mysql_user:
    login_user: root
    login_password: '{{mysql_root_password}}'
    name: andrew
    password: '{{mysql_andrew_password}}'
    priv: '*.*:ALL'
    state: present
    check_implicit_admin: yes

- name: Set up ~andrew/.my.cnf
  template: src=andrew.my.cnf dest=/home/andrew/.my.cnf owner=andrew group=defaria mode=0600

- mysql_user:
    login_user: root
    login_password: '{{mysql_root_password}}'
    name: maps
    password: '{{mysql_maps_password}}'
    priv: 'MAPS.*:ALL'
    state: present
    check_implicit_admin: yes

- name: Dump current MAPS database
  become_user: andrew
  become: yes
  shell: ssh defaria.com mysqldump -p{{mysql_andrew_password}} -B MAPS > /tmp/maps.dump

- name: Create MAPS database
  mysql_db:
    login_user: maps
    login_password: '{{mysql_maps_password}}'
    name: MAPS
    state: import
    target: /tmp/maps.dump

- name: Cleanup maps.dump
  file: path=tmp/maps.dump state=absent
